title: Neha Bora
email: nehabora91@gmail.com
description: Applied Scientist | Machine Learning Engineer | Physicist
baseurl: ""
url: "https://nbora0911.github.io"
github_username: nbora0911

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed 